config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'

  get 'welcome/index'
  get 'welcome/nombre'
  get 'welcome/recuperar'
  get 'welcome/actualizar'

end

app/models/user.rb
class User < ActiveRecord::Base
	def saludar
		"Hola, mi nombre es #{name}."
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
		@msj = String.new('Bienvenido!')
	end

	def nombre
		@name = params[:name]
		a = User.new
		a.name = @name
		a.save
		@saludo = a.saludar
	end

	def recuperar
		@users = User.all
		@params = params.slice(:sort, :name)
		#usrs = User.all
		#usrs.each{|a| a.destroy}
	end

	def actualizar
		@uname = params[:id]
		user = User.find_by(id: @uname)
		user.name = "#{user.name}(Actulizado)"
		user.save
		@users = User.all
		render "recuperar"
	end
end

app/views/welcome/index.html.erb
<h1>Esto es una prueba,</h1>

<p><%= @msj %></p>

<form action="/welcome/nombre">
	<h2>Ingrese su nombre:</h2>
	<input type="input" name="name">
	<input type="submit" value="Guardar">
</form>

<p>Para ver los usuarios existentes haga click <%= link_to "aqui", "/welcome/recuperar" %></p>

app/views/welcome/nombre.html.erb
<h1>Formulario procesado</h1>

<p>Su nombre es: <%= @name %></p>

<p>Su saludo es: <%= @saludo %></p>

<p>Su usuario ha sido registrado en la base de datos,
para cargarlo haga click <%= link_to "aqui", "/welcome/recuperar" %></p>

app/views/welcome/recuperar.html.erb
<h1>Estos son todos los usuarios registrados hata ahora</h1>

<% @users.each do |u| %>
    <%= u.name %><%= link_to " edit", welcome_actualizar_path(id: u.id) %><br>
<% end %>

<p>Gracias por participar</p>